baseURL = 'https://tan_amy.github.io'
languageCode = 'en-us'
title = 'Our Wedding Photos â¤'
theme = 'paper'

enableInlineShortcodes = 'true' #å…è®¸å†…è”çŸ­ç 
enableEmoji = 'true'   #å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT = 'true' #å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage = 'true' #è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

buildDrafts = 'false'
buildFuture = 'false'
buildExpired = 'false'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
identifier = "shanghai"
name = "ä¸Šæµ·/ğŸ‡¨ğŸ‡³"
url = "/shanghai"
weight = 10

[[menu.main]]
identifier = "chengdu"
name = "æˆéƒ½/ğŸ‡¨ğŸ‡³"
url = "/chengdu"
weight = 20

[[menu.main]]
identifier = "australia"
name = "æ¾³æ´²/ğŸ‡¦ğŸ‡º"
url = "/australia/"
weight = 30



[params]
author = "Chris"
description = "There need to be add description"
#twitter = ''                # twitter.com/YOUR_TWITTER_ID
#   github = ''                  # github.com/YOUR_GITHUB_ID
instagram = ''            # instagram.com/YOUR_INSTAGRAM_ID
avatar = ""
fancybox = true

[taxonomies]
tag = "tags"

[assets]
favicon = "img/appe-touch-icon.png"
favicon16x16 = "img/appe-touch-icon.png"
favicon32x32 = "img/appe-touch-icon.png"
apple_touch_icon = "img/appe-touch-icon.png"
safari_pinned_tab = "img/appe-touch-icon.png"
